### ISSUE TITLE
The Apk Can't Installed in My Android, What Should I Do?

### ISSUE THREAD

**Issue by xgorn** [AyraHikari/ayra_sticker_maker#1]

**Comment by AyraHikari** [comment]
Make sure your device has Android 4.0.3 or above
Also currently this apk only support for 64-bit AArch64 (arm64-v8a) device only

**Comment by xgorn** [comment]
Is it possible to change it to armeabi-v7a ??

**Comment by AyraHikari** [comment]
Yes, i can build a new one
If you or anyone can test it

**Comment by xgorn** [comment]
I can test it sir.. Thank you sir

**Comment by AyraHikari** [comment]
Sorry for late reply
Can you test this?
Just extract and install apk inside zip
[AyraStickers_v1.1.2.zip](https://github.com/AyraHikari/ayra_sticker_maker/files/5114748/AyraStickers_v1.1.2.zip)

**Comment by xgorn** [comment]
It is worked, thank you sir🙏

**Comment by AyraHikari** [comment]
Alright, i will upload that in release, thanks for testing

**Comment by xgorn** [comment]
it's installed btw, but it didn't work to processing the sticker pack😅 (maybe crassed)
